name: docker-build-image

on:
  push:
    branches:
      - 'main'
    tags:
      - "v*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/fdiwg/dcf-shiny
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
          labels: |
            org.opencontainers.image.url=https://github.com/fdiwg/dcf-shiny
            org.opencontainers.image.source=https://github.com/fdiwg/dcf-shiny
            org.opencontainers.image.title=dcf-shiny
            org.opencontainers.image.description=A shiny app in support of data collection frameworks
            org.opencontainers.image.vendor=UN-FAO
            org.opencontainers.image.author=UN-FAO
      - name: Login to image repository
        if: github.ref_type == 'tag'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
